# Create a flask server docker
services:
  # Python 3.10 container for the dependencies
  web:
    # Build a docker container from the Dockerfile
    build:
      context: .
      args:
        GIT_URL: ${GIT_URL}
    ports:
      - "5600:5000"
    env_file: .env